@startuml

hide empty members

package "RTPS" <<Cloud>> {
    class Publisher
}

package "Connector" <<Rectangle>> {
    class Reader
    class TransformationLibrary
    class Writer
}

package "Other Protocol" <<Cloud>> {
    class OtherReader
}

Publisher -right-> Reader
Reader -right-> TransformationLibrary
TransformationLibrary -right-> Writer

OtherReader <- Writer

@enduml